server:
    port: 8080

spring:
    application:
        name: ecommerce
    datasource:
        username: root
        password: password
        url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true